# ترجمات نصوص بوت واتساب «فنّي» (English + اردو).
#
# - المفتاح = النص العربي بالضبط كما يُمرَّر لـ tr(...) — أي تعديل على النص العربي بالكود
#   لازم ينعكس هنا وإلا يرجع العربي للمستخدم (ما تطلع رسالة فاضية أبدًا).
# - المتغيرات {name} وغيرها لازم تبقى بكل ترجمة.
# - حدود واتساب تنطبق على كل لغة: عنوان الزر ≤ 20، عنوان صف القائمة ≤ 24، الوصف ≤ 72،
#   زر فتح القائمة ≤ 20، عنوان القسم ≤ 24، التذييل ≤ 60.
# - SERVICES: أسماء الخدمات للعرض فقط (تنحفظ بالقاعدة عربي دائمًا).

TEXTS: dict[str, dict[str, str]] = {
    "🌍 لتغيير الدولة اكتب: دولة": {"en": "🌍 To change country, type: country", "ur": "🌍 ملک بدلنے کے لیے لکھیں: ملک"},
    "➕ مهنتي ليست هنا": {"en": "➕ My job isn't listed", "ur": "➕ میرا پیشہ یہاں نہیں"},
    "اعرض كل المهن": {"en": "Show all professions", "ur": "تمام پیشے دکھائیں"},
    "أهلًا بك {name} 👋\nما هي مهنتك؟ اضغط الزر، وحدّد مهنتك ☑️ — ويمكنك تحديد مهنتين.": {
        "en": "Welcome {name} 👋\nWhat's your profession? Tap the button and tick yours ☑️ — you can pick two.",
        "ur": "خوش آمدید {name} 👋\nآپ کا پیشہ کیا ہے؟ بٹن دبائیں اور اپنا پیشہ منتخب کریں ☑️ — آپ دو پیشے بھی چن سکتے ہیں۔"},
    "حدّد مهنتك (مهنة أو مهنتان):": {"en": "Pick your profession (one or two):", "ur": "اپنا پیشہ منتخب کریں (ایک یا دو):"},
    "➕ إضافة مهنة أخرى": {"en": "➕ Add another job", "ur": "➕ دوسرا پیشہ"},
    # ─────────── المهنة الثانية ───────────
    "💡 يمكنك إضافة مهنة ثانية بعد إكمال التسجيل.": {
        "en": "💡 You can add a second profession after finishing registration.",
        "ur": "💡 رجسٹریشن مکمل ہونے کے بعد آپ دوسرا پیشہ بھی شامل کر سکتے ہیں۔"},
    "هذه مهنتك الأولى نفسها 🙂 اختر مهنة أخرى.": {
        "en": "That's already your first profession 🙂 Pick a different one.",
        "ur": "یہ تو آپ کا پہلا پیشہ ہی ہے 🙂 کوئی دوسرا منتخب کریں۔"},
    "🔄 تغيير المهنة الثانية": {"en": "🔄 Change 2nd profession", "ur": "🔄 دوسرا پیشہ بدلیں"},
    "🗑️ حذف المهنة الثانية": {"en": "🗑️ Remove 2nd profession", "ur": "🗑️ دوسرا پیشہ ہٹائیں"},
    "➕ إضافة مهنة ثانية": {"en": "➕ Add 2nd profession", "ur": "➕ دوسرا پیشہ شامل کریں"},
    "بنفس مدينتك وأحيائك": {"en": "Same city & districts", "ur": "اسی شہر اور محلوں میں"},
    "اختر": {"en": "Choose", "ur": "منتخب کریں"},
    "تعديل بياناتي": {"en": "Edit my info", "ur": "معلومات میں ترمیم"},
    "➕ اختر مهنتك الثانية 👇 (ستظهر بها للعملاء في نفس مدينتك وأحيائك)\nأو اضغط «المزيد»، أو اكتب اسمها.": {
        "en": "➕ Choose your second profession 👇 (customers will see you for it in the same city & districts)\nOr tap «More», or type its name.",
        "ur": "➕ اپنا دوسرا پیشہ منتخب کریں 👇 (اسی شہر اور محلوں میں گاہک آپ کو اس کے لیے بھی دیکھیں گے)\nیا «مزید» دبائیں، یا اس کا نام لکھیں۔"},
    # ─────────── تعديل بيانات الفني ───────────
    "✏️ تعديل بياناتي": {"en": "✏️ Edit my info", "ur": "✏️ معلومات میں ترمیم"},
    "🛠️ الخدمات": {"en": "🛠️ Services", "ur": "🛠️ سروسز"},
    "📍 الأحياء": {"en": "📍 Districts", "ur": "📍 محلے"},
    "👷 الاسم": {"en": "👷 Name", "ur": "👷 نام"},
    "✏️ ماذا تريد أن تعدّل؟ 👇\n(لتغيير المهنة: احذف حسابك بكتابة d ثم سجّل من جديد)": {
        "en": "✏️ What would you like to edit? 👇\n(To change your profession: delete your account by typing d, then register again)",
        "ur": "✏️ آپ کیا تبدیل کرنا چاہتے ہیں؟ 👇\n(پیشہ بدلنے کے لیے: d لکھ کر اپنا اکاؤنٹ حذف کریں، پھر دوبارہ رجسٹر کریں)"},
    "✍️ اكتب الاسم الجديد (الاسم الذي سيظهر للعملاء):": {
        "en": "✍️ Type the new name (the name customers will see):",
        "ur": "✍️ نیا نام لکھیں (وہ نام جو گاہکوں کو نظر آئے گا):"},
    "✅ تم تحديث بياناتك.": {"en": "✅ Your info has been updated.", "ur": "✅ آپ کی معلومات اپ ڈیٹ ہو گئیں۔"},
    # ─────────── القائمة الرئيسية ───────────
    "أهلًا {name} 👋": {"en": "Hi {name} 👋", "ur": "السلام علیکم {name} 👋"},
    "أهلًا بك 👋": {"en": "Welcome 👋", "ur": "خوش آمدید 👋"},
    "{hi}\nهنا «فنّي» 🛠️ نصلك بأقرب فنّي: سبّاك، كهربائي، تكييف، نجّار، وأكثر من 60 مهنة في السعودية ومصر ودول الخليج.\n\n📢 قناة فنّي: {url}\n\nماذا تريد أن تفعل؟": {
        "en": "{hi}\nThis is «Fanni» 🛠️ We connect you with the nearest technician: plumber, electrician, AC, carpenter and 60+ trades in Saudi Arabia, Egypt and the Gulf.\n\n📢 Fanni channel: {url}\n\nWhat would you like to do?",
        "ur": "{hi}\nیہ «فنی» ہے 🛠️ ہم آپ کو قریب ترین ٹیکنیشن سے ملاتے ہیں: پلمبر، الیکٹریشن، اے سی، بڑھئی اور 60 سے زیادہ کام، سعودی عرب، مصر اور خلیجی ممالک میں۔\n\n📢 فنی چینل: {url}\n\nآپ کیا کرنا چاہتے ہیں؟",
    },
    "🔍 ابحث عن فني": {"en": "🔍 Find a technician", "ur": "🔍 ٹیکنیشن تلاش کریں"},
    "🛠️ أنا فني": {"en": "🛠️ I'm a technician", "ur": "🛠️ میں ٹیکنیشن ہوں"},
    "s للبداية • d لحذف بياناتك": {"en": "s = start • d = delete your data", "ur": "s = شروع • d = اپنا ڈیٹا ڈیلیٹ کریں"},
    "📢 تابع قناة «فنّي» على واتساب: عروض، مهن جديدة، ونصائح صيانة.": {
        "en": "📢 Follow the «Fanni» WhatsApp channel: offers, new trades and maintenance tips.",
        "ur": "📢 واٹس ایپ پر «فنی» چینل فالو کریں: آفرز، نئے کام اور مرمت کے مشورے۔",
    },
    "فتح القناة": {"en": "Open channel", "ur": "چینل کھولیں"},
    "مرحبًا بك 🙌 يتم التسجيل كفنّي حاليًا عن طريق بوت «فنّي» على تلغرام — مجانًا ويستغرق دقيقتين، وبعدها تظهر للعملاء الذين يبحثون هنا في واتساب وفي تلغرام.": {
        "en": "Welcome 🙌 Technician sign-up is currently done through the «Fanni» Telegram bot — it's free and takes two minutes, then you'll appear to customers searching here on WhatsApp and on Telegram.",
        "ur": "خوش آمدید 🙌 ٹیکنیشن کی رجسٹریشن ابھی ٹیلیگرام پر «فنی» بوٹ کے ذریعے ہوتی ہے — مفت ہے اور دو منٹ لگتے ہیں، پھر آپ واٹس ایپ اور ٹیلیگرام پر تلاش کرنے والے گاہکوں کو نظر آئیں گے۔",
    },
    "سجّل مجانًا": {"en": "Sign up free", "ur": "مفت رجسٹر کریں"},

    # ─────────── حذف البيانات ───────────
    "• تسجيلك كفنّي ({name})، ولن تظهر للعملاء بعد الآن": {
        "en": "• Your technician registration ({name}) — you will no longer appear to customers",
        "ur": "• بطور ٹیکنیشن آپ کی رجسٹریشن ({name})، آپ گاہکوں کو مزید نظر نہیں آئیں گے",
    },
    "• اشتراكك المدفوع الحالي، دون استرجاع المبلغ": {
        "en": "• Your current paid subscription, with no refund",
        "ur": "• آپ کی موجودہ ادا شدہ سبسکرپشن، رقم واپس نہیں ہوگی",
    },
    "• سجل عمليات البحث (ما بحثت عنه وأين)": {
        "en": "• Your search history (what you searched for and where)",
        "ur": "• آپ کی تلاش کی ہسٹری (کیا اور کہاں تلاش کیا)",
    },
    "• سجل الفنيين الذين تواصلت معهم": {
        "en": "• The technicians you contacted",
        "ur": "• جن ٹیکنیشنز سے آپ نے رابطہ کیا ان کا ریکارڈ",
    },
    "• محادثتك الحالية مع «فنّي»": {"en": "• Your current chat with «Fanni»", "ur": "• «فنی» کے ساتھ آپ کی موجودہ گفتگو"},
    "🗑️ هل تريد حذف بياناتك من «فنّي» نهائيًا؟\n\nسيُحذف ما يلي:\n{items}\n\n⚠️ لا يمكن التراجع عن هذا الإجراء.": {
        "en": "🗑️ Do you want to permanently delete your data from «Fanni»?\n\nThe following will be deleted:\n{items}\n\n⚠️ This cannot be undone.",
        "ur": "🗑️ کیا آپ «فنی» سے اپنا ڈیٹا ہمیشہ کے لیے ڈیلیٹ کرنا چاہتے ہیں؟\n\nیہ سب ڈیلیٹ ہو جائے گا:\n{items}\n\n⚠️ یہ عمل واپس نہیں ہو سکتا۔",
    },
    "🗑️ نعم، احذف": {"en": "🗑️ Yes, delete", "ur": "🗑️ ہاں، ڈیلیٹ کریں"},
    "لا، رجوع": {"en": "No, go back", "ur": "نہیں، واپس"},
    "✅ تم حذف جميع بياناتك من «فنّي» نهائيًا. يمكنك العودة إلى استخدام الخدمة في أي وقت.": {
        "en": "✅ All your data has been permanently deleted from «Fanni». You can come back and use the service anytime.",
        "ur": "✅ «فنی» سے آپ کا سارا ڈیٹا ہمیشہ کے لیے ڈیلیٹ ہو گیا۔ آپ کسی بھی وقت دوبارہ سروس استعمال کر سکتے ہیں۔",
    },

    # ─────────── اختيار المهنة (البحث) ───────────
    "{note}ما المهنة التي تبحث عنها؟ اختر من القائمة 👇\nأو اكتب اسمها مباشرة (مثل: سباك)": {
        "en": "{note}Which trade are you looking for? Pick from the list 👇\nor type its name (e.g. plumber)",
        "ur": "{note}آپ کو کس کام کا ٹیکنیشن چاہیے؟ لسٹ سے منتخب کریں 👇\nیا اس کا نام لکھیں (جیسے: پلمبر)",
    },
    "اختر المهنة": {"en": "Choose a trade", "ur": "کام منتخب کریں"},
    "🔍 بحث عن فني": {"en": "🔍 Find a technician", "ur": "🔍 ٹیکنیشن کی تلاش"},
    "الأكثر طلبًا": {"en": "Most requested", "ur": "سب سے زیادہ مانگ"},
    "📋 باقي المهن:": {"en": "📋 Other trades:", "ur": "📋 باقی کام:"},
    "✍️ اكتب *رقم* المهنة (مثل: 3) أو اسمها.": {
        "en": "✍️ Type the trade's *number* (e.g. 3) or its name.",
        "ur": "✍️ کام کا *نمبر* (جیسے: 3) یا اس کا نام لکھیں۔",
    },
    "➕ المزيد": {"en": "➕ More", "ur": "➕ مزید"},
    "باقي المهن ({n} مهنة)": {"en": "Other trades ({n})", "ur": "باقی کام ({n})"},
    "اختر مجال المهنة من القائمة 👇\nأو اكتب اسم المهنة مباشرة (مثل: سباك، كهربائي، تكييف)": {
        "en": "Choose a field from the list 👇\nor type the trade name (e.g. plumber, electrician, AC)",
        "ur": "لسٹ سے شعبہ منتخب کریں 👇\nیا کام کا نام لکھیں (جیسے: پلمبر، الیکٹریشن، اے سی)",
    },
    "اختر المجال": {"en": "Choose a field", "ur": "شعبہ منتخب کریں"},
    "المجالات": {"en": "Fields", "ur": "شعبے"},
    "المزيد ⬅️": {"en": "More ➡️", "ur": "مزید ⬅️"},
    "باقي المجالات": {"en": "Other fields", "ur": "باقی شعبے"},
    "➡️ السابق": {"en": "⬅️ Previous", "ur": "➡️ پچھلا"},
    "باقي {n} مهنة": {"en": "{n} more trades", "ur": "مزید {n} کام"},
    "↩️ العودة إلى المجالات": {"en": "↩️ Back to fields", "ur": "↩️ شعبوں پر واپس"},
    "اختر المهنة 👇": {"en": "Choose a trade 👇", "ur": "کام منتخب کریں 👇"},
    "المهن": {"en": "Trades", "ur": "کام"},
    "هذا الرقم غير موجود في القائمة 🤔 اكتب رقمًا صحيحًا أو اسم المهنة.": {
        "en": "That number isn't on the list 🤔 Type a valid number or the trade name.",
        "ur": "یہ نمبر لسٹ میں نہیں ہے 🤔 صحیح نمبر یا کام کا نام لکھیں۔",
    },
    "📋 كل المهن": {"en": "📋 All trades", "ur": "📋 تمام کام"},
    "وجدت أكثر من مهنة قريبة من «{q}» — اختر المهنة المقصودة 👇": {
        "en": "I found several trades similar to «{q}» — pick the one you mean 👇",
        "ur": "«{q}» سے ملتے جلتے کئی کام ملے — اپنا مطلوبہ کام منتخب کریں 👇",
    },
    "نتائج البحث": {"en": "Search results", "ur": "تلاش کے نتائج"},
    "لم أجد مهنة باسم «{q}» 🤔\n\n": {
        "en": "I couldn't find a trade called «{q}» 🤔\n\n",
        "ur": "«{q}» نام کا کوئی کام نہیں ملا 🤔\n\n",
    },
    "حسنًا ✅ «{name}»\n📍 أرسل موقعك من الزر أدناه، وسنعرض لك أقرب الفنيين إليك.": {
        "en": "OK ✅ «{name}»\n📍 Send your location using the button below and we'll show you the nearest technicians.",
        "ur": "ٹھیک ہے ✅ «{name}»\n📍 نیچے والے بٹن سے اپنی لوکیشن بھیجیں، ہم آپ کو قریب ترین ٹیکنیشن دکھائیں گے۔",
    },
    "أو اختر مدينتك وحيّك يدويًا:": {
        "en": "Or choose your city and district manually:",
        "ur": "یا اپنا شہر اور محلہ خود منتخب کریں:",
    },
    "🏙️ اختيار يدوي": {"en": "🏙️ Choose manually", "ur": "🏙️ خود منتخب کریں"},
    "📍 أرسل موقعك (📎 ← الموقع)، أو اختر مدينتك يدويًا:": {
        "en": "📍 Send your location (📎 → Location), or choose your city manually:",
        "ur": "📍 اپنی لوکیشن بھیجیں (📎 ← لوکیشن)، یا اپنا شہر خود منتخب کریں:",
    },

    # ─────────── الموقع اليدوي ───────────
    "لم نتمكن من تحديد مدينتك من الموقع 😅 اختر يدويًا:": {
        "en": "We couldn't detect your city from that location 😅 Please choose manually:",
        "ur": "لوکیشن سے آپ کا شہر معلوم نہیں ہو سکا 😅 خود منتخب کریں:",
    },
    "اختر الدولة 👇": {"en": "Choose your country 👇", "ur": "ملک منتخب کریں 👇"},
    "اختر الدولة": {"en": "Choose country", "ur": "ملک منتخب کریں"},
    "الدول": {"en": "Countries", "ur": "ممالک"},
    "📍 مناطق {country} 👇": {"en": "📍 Regions of {country} 👇", "ur": "📍 {country} کے علاقے 👇"},
    "✍️ اكتب *رقم* المنطقة.": {"en": "✍️ Type the region *number*.", "ur": "✍️ علاقے کا *نمبر* لکھیں۔"},
    "اكتب رقمًا من 1 إلى {n} 🙏": {"en": "Type a number from 1 to {n} 🙏", "ur": "1 سے {n} تک کوئی نمبر لکھیں 🙏"},
    "لا توجد مدن مسجلة في هذه المنطقة حاليًا.": {
        "en": "There are no cities listed in this region yet.",
        "ur": "اس علاقے میں فی الحال کوئی شہر درج نہیں ہے۔",
    },
    "🏙️ اختر المدينة 👇": {"en": "🏙️ Choose your city 👇", "ur": "🏙️ شہر منتخب کریں 👇"},
    "✍️ اكتب *رقم* المدينة.": {"en": "✍️ Type the city *number*.", "ur": "✍️ شہر کا *نمبر* لکھیں۔"},
    "🌍 كل {city}": {"en": "🌍 All of {city}", "ur": "🌍 پورا {city}"},
    "كل أحياء المدينة": {"en": "All districts in the city", "ur": "شہر کے تمام محلے"},
    "📍 اختر الحي في {city} 👇": {"en": "📍 Choose your district in {city} 👇", "ur": "📍 {city} میں اپنا محلہ منتخب کریں 👇"},
    "اختر الحي": {"en": "Choose district", "ur": "محلہ منتخب کریں"},
    "الأحياء": {"en": "Districts", "ur": "محلے"},
    "📍 أحياء {city} 👇": {"en": "📍 Districts of {city} 👇", "ur": "📍 {city} کے محلے 👇"},
    "📍 أحياء {city} — مقسّمة حسب المنطقة 👇": {
        "en": "📍 Districts of {city} — grouped by area 👇",
        "ur": "📍 {city} کے محلے — علاقے کے لحاظ سے 👇",
    },
    "✍️ اكتب *رقم* حيّك (أو اسمه).": {
        "en": "✍️ Type your district *number* (or its name).",
        "ur": "✍️ اپنے محلے کا *نمبر* (یا نام) لکھیں۔",
    },
    "اكتب رقمًا من 1 إلى {n}، أو # لكل المدينة 🙏": {
        "en": "Type a number from 1 to {n}, or # for the whole city 🙏",
        "ur": "1 سے {n} تک نمبر لکھیں، یا پورے شہر کے لیے # 🙏",
    },
    "🔎 الأحياء التي تحتوي على «{q}»:\n{lines}\n\n✍️ اكتب *رقم* حيّك.": {
        "en": "🔎 Districts containing «{q}»:\n{lines}\n\n✍️ Type your district *number*.",
        "ur": "🔎 وہ محلے جن میں «{q}» ہے:\n{lines}\n\n✍️ اپنے محلے کا *نمبر* لکھیں۔",
    },
    "✍️ اكتب *رقم* حيّك من القائمة أعلاه 👆 أو # لكل المدينة.": {
        "en": "✍️ Type your district *number* from the list above 👆 or # for the whole city.",
        "ur": "✍️ اوپر والی لسٹ سے اپنے محلے کا *نمبر* لکھیں 👆 یا پورے شہر کے لیے #۔",
    },
    "لم أجد حيًّا يحتوي على «{q}».": {
        "en": "I couldn't find a district containing «{q}».",
        "ur": "«{q}» والا کوئی محلہ نہیں ملا۔",
    },
    "المدينة": {"en": "the city", "ur": "شہر"},
    "اختر حيّك من النتائج 👇": {"en": "Choose your district from the results 👇", "ur": "نتائج میں سے اپنا محلہ منتخب کریں 👇"},
    "لم أجد حيًّا باسم «{q}» في {city} 🤔 اكتب رقم الحي من القائمة، أو # لكل المدينة.": {
        "en": "I couldn't find a district called «{q}» in {city} 🤔 Type the district number from the list, or # for the whole city.",
        "ur": "{city} میں «{q}» نام کا کوئی محلہ نہیں ملا 🤔 لسٹ سے محلے کا نمبر لکھیں، یا پورے شہر کے لیے #۔",
    },
    # عناوين مجموعات الأحياء (المدن الكبيرة)
    "📍 أحياء أخرى": {"en": "📍 Other districts", "ur": "📍 دیگر محلے"},
    "🧭 {base} — حول {landmark}": {"en": "🧭 {base} — around {landmark}", "ur": "🧭 {base} — {landmark} کے آس پاس"},
    "وسط {city}": {"en": "Central {city}", "ur": "وسطی {city}"},
    "{dir} {city}": {"en": "{dir} {city}", "ur": "{dir} {city}"},
    "شمال": {"en": "North", "ur": "شمالی"},
    "شمال شرق": {"en": "Northeast", "ur": "شمال مشرقی"},
    "شرق": {"en": "East", "ur": "مشرقی"},
    "جنوب شرق": {"en": "Southeast", "ur": "جنوب مشرقی"},
    "جنوب": {"en": "South", "ur": "جنوبی"},
    "جنوب غرب": {"en": "Southwest", "ur": "جنوب مغربی"},
    "غرب": {"en": "West", "ur": "مغربی"},
    "شمال غرب": {"en": "Northwest", "ur": "شمال مغربی"},

    # ─────────── النتائج والتواصل ───────────
    "لم نجد نتائج في {nb}، وهذه نتائج {city} كاملة 👇\n": {
        "en": "No results in {nb}, so here are results for all of {city} 👇\n",
        "ur": "{nb} میں کوئی نتیجہ نہیں ملا، یہ پورے {city} کے نتائج ہیں 👇\n",
    },
    "عذرًا، لا يوجد حاليًا فنيون في مهنة «{pname}» في {city} ولا في المدن القريبة منها 😔\nسجّلنا طلبك، ونعمل على إضافة فنيين في منطقتك قريبًا.\n\nللبحث من جديد اكتب s": {
        "en": "Sorry, there are currently no «{pname}» technicians in {city} or nearby cities 😔\nWe've noted your request and are working on adding technicians in your area soon.\n\nTo search again, type s",
        "ur": "معذرت، ابھی {city} اور قریبی شہروں میں «{pname}» کا کوئی ٹیکنیشن موجود نہیں 😔\nہم نے آپ کی درخواست نوٹ کر لی ہے، جلد آپ کے علاقے میں ٹیکنیشن شامل کریں گے۔\n\nدوبارہ تلاش کے لیے s لکھیں",
    },
    "• {name} — تبعد {km} كم": {"en": "• {name} — {km} km away", "ur": "• {name} — {km} کلومیٹر دور"},
    "لا يوجد حاليًا فنيون في مهنة «{pname}» في {city} 😔\nيتوفر فنيون في هذه المدن القريبة 👇\n{lines}": {
        "en": "There are currently no «{pname}» technicians in {city} 😔\nTechnicians are available in these nearby cities 👇\n{lines}",
        "ur": "ابھی {city} میں «{pname}» کا کوئی ٹیکنیشن نہیں 😔\nان قریبی شہروں میں ٹیکنیشن دستیاب ہیں 👇\n{lines}",
    },
    "المدينة كاملة 🌍": {"en": "Whole city 🌍", "ur": "پورا شہر 🌍"},
    "{city} — المدينة كاملة 🌍": {"en": "{city} — whole city 🌍", "ur": "{city} — پورا شہر 🌍"},
    "هؤلاء جميع الفنيين المتاحين 👌": {"en": "That's all the available technicians 👌", "ur": "یہ تمام دستیاب ٹیکنیشن ہیں 👌"},
    "🔄 بحث جديد": {"en": "🔄 New search", "ur": "🔄 نئی تلاش"},
    "⬇️ عرض المزيد": {"en": "⬇️ Show more", "ur": "⬇️ مزید دکھائیں"},
    'هؤلاء هم الفنيون الذين عرضناهم لك في هذه المهنة خلال آخر 24 ساعة، ويمكنك البحث عن فنيين آخرين بعد انقضائها.\n': {"en": "These are the technicians we showed you for this trade in the last 24 hours. You can search for other technicians once that period ends.\n", "ur": "یہ وہی ٹیکنیشن ہیں جو ہم نے پچھلے 24 گھنٹوں میں اس پیشے کے لیے آپ کو دکھائے تھے۔ یہ مدت ختم ہونے کے بعد آپ دوسرے ٹیکنیشن تلاش کر سکتے ہیں۔\n"},
    'بحثت في مكانين عن هذه المهنة خلال آخر 24 ساعة، وهو الحد المسموح به. يمكنك البحث في مكان آخر بعد انقضائها، أو البحث من جديد في أحد المكانين لترى الفنيين أنفسهم.\n\nللبحث من جديد اكتب s': {"en": 'You have searched two places for this trade in the last 24 hours, which is the limit. You can search another place once that period ends, or search one of the two places again to see the same technicians.\n\nTo search again type s', "ur": 'آپ نے پچھلے 24 گھنٹوں میں اس پیشے کے لیے دو جگہوں پر تلاش کی ہے، جو حد ہے۔ یہ مدت ختم ہونے کے بعد آپ کسی اور جگہ تلاش کر سکتے ہیں، یا انہی دو جگہوں میں سے کسی ایک میں دوبارہ تلاش کر کے وہی ٹیکنیشن دیکھ سکتے ہیں۔\n\nدوبارہ تلاش کے لیے s لکھیں'},
    "بقي {n} من الفنيين": {"en": "{n} more technicians", "ur": "مزید {n} ٹیکنیشن"},
    "وجدنا {n} من فنيي «{pname}» 👍\nاضغط «عرض الفنيين» واختر أحدهم، وسنفتح لك محادثته على واتساب مباشرة.": {
        "en": "We found {n} «{pname}» technicians 👍\nTap «View technicians» and pick one — we'll open a WhatsApp chat with them right away.",
        "ur": "«{pname}» کے {n} ٹیکنیشن ملے 👍\n«ٹیکنیشن دیکھیں» دبائیں اور کسی ایک کو منتخب کریں، ہم فوراً واٹس ایپ پر اس سے چیٹ کھول دیں گے۔",
    },
    "بقي {n} من فنيي «{pname}» 👇": {"en": "{n} more «{pname}» technicians 👇", "ur": "«{pname}» کے مزید {n} ٹیکنیشن 👇"},
    "عرض الفنيين": {"en": "View technicians", "ur": "ٹیکنیشن دیکھیں"},
    "الترتيب بالتناوب العادل بين الفنيين": {"en": "Order rotates fairly between technicians", "ur": "ترتیب تمام ٹیکنیشنز میں باری باری بدلتی ہے"},
    "الفنيين": {"en": "Technicians", "ur": "ٹیکنیشن"},
    "⏰ نتائج هذا البحث قديمة (مضى عليها أكثر من يوم). ابدأ بحثًا جديدًا لترى الفنيين المتاحين الآن 👇": {
        "en": "⏰ These search results are old (more than a day). Start a new search to see who's available now 👇",
        "ur": "⏰ یہ تلاش کے نتائج پرانے ہیں (ایک دن سے زیادہ)۔ ابھی دستیاب ٹیکنیشن دیکھنے کے لیے نئی تلاش کریں 👇",
    },
    "عذرًا، هذا الفني غير متاح حاليًا 🙏 اختر فنيًا آخر من القائمة، أو اكتب s لبدء بحث جديد.": {
        "en": "Sorry, this technician isn't available right now 🙏 Pick another one from the list, or type s to start a new search.",
        "ur": "معذرت، یہ ٹیکنیشن ابھی دستیاب نہیں 🙏 لسٹ سے کوئی اور منتخب کریں، یا نئی تلاش کے لیے s لکھیں۔",
    },
    "{card}\n\n📞 هذا الرقم للاتصال فقط (بدون واتساب): {number}": {
        "en": "{card}\n\n📞 This number is for calls only (no WhatsApp): {number}",
        "ur": "{card}\n\n📞 یہ نمبر صرف کال کے لیے ہے (واٹس ایپ نہیں): {number}",
    },
    "{card}\n\nاضغط الزر لفتح المحادثة معه 👇": {
        "en": "{card}\n\nTap the button to open a chat with them 👇",
        "ur": "{card}\n\nان سے چیٹ کھولنے کے لیے بٹن دبائیں 👇",
    },
    "🧹 هل تريد حذف المحادثة تلقائيًا؟ اضغط على اسم المحادثة في الأعلى ← «الرسائل المؤقتة» ← 24 ساعة": {
        "en": "🧹 Want this chat to clear itself? Tap the chat name at the top → «Disappearing messages» → 24 hours",
        "ur": "🧹 کیا آپ چاہتے ہیں کہ چیٹ خود ڈیلیٹ ہو جائے؟ اوپر چیٹ کے نام پر دبائیں ← «غائب ہونے والے پیغامات» ← 24 گھنٹے",
    },
    "💬 فتح المحادثة": {"en": "💬 Open chat", "ur": "💬 چیٹ کھولیں"},
    "يمكنك العودة إلى القائمة واختيار فنّي آخر": {
        "en": "You can go back to the list and pick another technician",
        "ur": "آپ لسٹ پر واپس جا کر کوئی اور ٹیکنیشن چن سکتے ہیں",
    },

    # ─────────── تسجيل الفني ───────────
    "مرحبًا بك 🙌 سنسجّلك في «فنّي» مجانًا خلال دقيقة، لتظهر للعملاء في واتساب وتلغرام.\n\n✍️ اكتب اسمك (الاسم الذي سيظهر للعملاء):": {
        "en": "Welcome 🙌 We'll register you on «Fanni» for free in a minute, so customers can find you on WhatsApp and Telegram.\n\n✍️ Type your name (the name customers will see):",
        "ur": "خوش آمدید 🙌 ہم ایک منٹ میں آپ کو «فنی» پر مفت رجسٹر کریں گے، تاکہ واٹس ایپ اور ٹیلیگرام پر گاہک آپ کو دیکھ سکیں۔\n\n✍️ اپنا نام لکھیں (جو نام گاہکوں کو نظر آئے گا):",
    },
    "اكتب اسمًا يتراوح طوله بين حرفين و40 حرفًا 🙏": {
        "en": "Please type a name between 2 and 40 characters 🙏",
        "ur": "2 سے 40 حروف کے درمیان نام لکھیں 🙏",
    },
    "✅ مشترك — تظهر لجميع العملاء دون حد": {
        "en": "✅ Subscribed — you're shown to all customers without limits",
        "ur": "✅ سبسکرائبڈ — آپ بغیر حد کے تمام گاہکوں کو نظر آتے ہیں",
    },
    "📊 فرص التواصل المجانية: استخدمت {used} من {limit}": {
        "en": "📊 Free contacts: you've used {used} of {limit}",
        "ur": "📊 مفت رابطے: آپ نے {limit} میں سے {used} استعمال کیے",
    },
    "⚠️ انتهت فرصك المجانية — رقمك لا يظهر للعملاء حاليًا. اضغط «💳 اشترك» أدناه لتعود إلى الظهور.": {
        "en": "⚠️ Your free contacts are used up — your number isn't shown to customers right now. Tap «💳 Subscribe» below to appear again.",
        "ur": "⚠️ آپ کے مفت رابطے ختم ہو گئے — ابھی آپ کا نمبر گاہکوں کو نظر نہیں آ رہا۔ دوبارہ نظر آنے کے لیے نیچے «💳 سبسکرائب» دبائیں۔",
    },
    "💳 اشترك": {"en": "💳 Subscribe", "ur": "💳 سبسکرائب"},
    "🔗 اربط بتلغرام": {"en": "🔗 Link Telegram", "ur": "🔗 ٹیلیگرام جوڑیں"},
    "أنت مسجّل في «فنّي» 👌\n\n{card}\n\n{line}": {
        "en": "You're registered on «Fanni» 👌\n\n{card}\n\n{line}",
        "ur": "آپ «فنی» پر رجسٹرڈ ہیں 👌\n\n{card}\n\n{line}",
    },
    "📢 تابع قناة «فنّي» على واتساب: {url}": {
        "en": "📢 Follow the «Fanni» WhatsApp channel: {url}",
        "ur": "📢 واٹس ایپ پر «فنی» چینل فالو کریں: {url}",
    },
    "📱 هل تريد التسجيل على هذا الرقم؟\n+{me}\n\n(هو الرقم الذي سيتواصل عليه العملاء عبر واتساب)": {
        "en": "📱 Do you want to register with this number?\n+{me}\n\n(This is the number customers will contact on WhatsApp)",
        "ur": "📱 کیا آپ اسی نمبر پر رجسٹر کرنا چاہتے ہیں؟\n+{me}\n\n(اسی نمبر پر گاہک واٹس ایپ سے رابطہ کریں گے)",
    },
    "✅ نعم، هذا الرقم": {"en": "✅ Yes, this number", "ur": "✅ ہاں، یہی نمبر"},
    "📱 رقم آخر": {"en": "📱 Another number", "ur": "📱 دوسرا نمبر"},
    "هذا الرقم مسجّل مسبقًا في «فنّي» باسم «{name}».": {
        "en": "This number is already registered on «Fanni» under the name «{name}».",
        "ur": "یہ نمبر پہلے سے «فنی» پر «{name}» کے نام سے رجسٹرڈ ہے۔",
    },
    "✍️ اكتب رقم واتساب الفني (مثل: 0501234567 أو 966501234567):": {
        "en": "✍️ Type the technician's WhatsApp number (e.g. 0501234567 or 966501234567):",
        "ur": "✍️ ٹیکنیشن کا واٹس ایپ نمبر لکھیں (جیسے: 0501234567 یا 966501234567):",
    },
    "الرقم غير صحيح 🙏 اكتبه مثل: 0501234567 أو 966501234567": {
        "en": "Invalid number 🙏 Type it like: 0501234567 or 966501234567",
        "ur": "نمبر درست نہیں 🙏 اس طرح لکھیں: 0501234567 یا 966501234567",
    },
    "الرقم +{phone} مسجّل مسبقًا في «فنّي» باسم «{name}». اكتب رقمًا آخر:": {
        "en": "The number +{phone} is already registered on «Fanni» under the name «{name}». Type another number:",
        "ur": "نمبر +{phone} پہلے سے «فنی» پر «{name}» کے نام سے رجسٹرڈ ہے۔ دوسرا نمبر لکھیں:",
    },
    "✅ سيُسجَّل الفني على الرقم +{phone}\n\n": {
        "en": "✅ The technician will be registered on +{phone}\n\n",
        "ur": "✅ ٹیکنیشن نمبر +{phone} پر رجسٹر ہوگا\n\n",
    },
    "⚠️ تجاوزت الحد المسموح لإرسال رموز التحقق اليوم. حاول غدًا، أو سجّل من جوال الفني نفسه.": {
        "en": "⚠️ You've reached today's limit for verification codes. Try tomorrow, or register from the technician's own phone.",
        "ur": "⚠️ آج کے لیے تصدیقی کوڈ بھیجنے کی حد پوری ہو گئی۔ کل کوشش کریں، یا ٹیکنیشن کے اپنے موبائل سے رجسٹر کریں۔",
    },
    "🔐 رمز التحقق لتسجيلك في «فنّي»: {code}\nلا تشاركه إلا مع الشخص الذي يسجّلك.": {
        "en": "🔐 Your «Fanni» registration verification code: {code}\nShare it only with the person registering you.",
        "ur": "🔐 «فنی» میں رجسٹریشن کا تصدیقی کوڈ: {code}\nیہ صرف اسی شخص کو دیں جو آپ کو رجسٹر کر رہا ہے۔",
    },
    "⚠️ تعذّر إرسال الرمز إلى +{phone}. تأكد أن الرقم صحيح وعليه واتساب، أو سجّل من جوال الفني نفسه.\n\n✍️ اكتب الرقم مرة أخرى:": {
        "en": "⚠️ Couldn't send the code to +{phone}. Make sure the number is correct and has WhatsApp, or register from the technician's own phone.\n\n✍️ Type the number again:",
        "ur": "⚠️ +{phone} پر کوڈ نہیں بھیجا جا سکا۔ تسلی کریں کہ نمبر درست ہے اور اس پر واٹس ایپ ہے، یا ٹیکنیشن کے اپنے موبائل سے رجسٹر کریں۔\n\n✍️ نمبر دوبارہ لکھیں:",
    },
    "📩 أرسلنا رمز تحقق إلى واتساب الرقم +{phone}.\nاطلب الرمز من صاحب الرقم، واكتبه هنا (صالح 10 دقائق):": {
        "en": "📩 We sent a verification code to WhatsApp number +{phone}.\nAsk the number's owner for the code and type it here (valid for 10 minutes):",
        "ur": "📩 ہم نے واٹس ایپ نمبر +{phone} پر تصدیقی کوڈ بھیجا ہے۔\nنمبر والے سے کوڈ لے کر یہاں لکھیں (10 منٹ کے لیے درست):",
    },
    "⌛ انتهت صلاحية الرمز. اكتب الرقم مرة أخرى لإرسال رمز جديد:": {
        "en": "⌛ The code has expired. Type the number again to get a new code:",
        "ur": "⌛ کوڈ کی میعاد ختم ہو گئی۔ نیا کوڈ لینے کے لیے نمبر دوبارہ لکھیں:",
    },
    "✅ تم التحقق من الرقم +{phone}\n\n": {"en": "✅ Number +{phone} verified\n\n", "ur": "✅ نمبر +{phone} کی تصدیق ہو گئی\n\n"},
    "❌ تجاوزت عدد المحاولات. اكتب الرقم مرة أخرى لإرسال رمز جديد:": {
        "en": "❌ Too many attempts. Type the number again to get a new code:",
        "ur": "❌ کوششیں ختم ہو گئیں۔ نیا کوڈ لینے کے لیے نمبر دوبارہ لکھیں:",
    },
    "❌ الرمز غير صحيح. حاول مرة أخرى (المتبقي: {left}):": {
        "en": "❌ Wrong code. Try again ({left} left):",
        "ur": "❌ کوڈ غلط ہے۔ دوبارہ کوشش کریں (باقی: {left}):",
    },
    "أهلًا بك {name} 👋\nما هي مهنتك؟ اختر من القائمة التالية، أو اضغط «المزيد» للقائمة الموسّعة (+{n} مهنة)، أو اكتب اسمها (مثل: سباك)": {
        "en": "Welcome {name} 👋\nWhat's your trade? Pick from the list, tap «More» for the full list (+{n} trades), or type its name (e.g. plumber)",
        "ur": "خوش آمدید {name} 👋\nآپ کا کام کیا ہے؟ لسٹ سے منتخب کریں، پوری لسٹ کے لیے «مزید» دبائیں (+{n} کام)، یا اس کا نام لکھیں (جیسے: پلمبر)",
    },
    "اختر مهنتك": {"en": "Choose your trade", "ur": "اپنا کام چنیں"},
    "تشرّفنا بك يا {name} 🌟\nاختر مجال مهنتك 👇 أو اكتب اسم مهنتك (مثل: سباك)": {
        "en": "Nice to meet you, {name} 🌟\nChoose your field 👇 or type your trade (e.g. plumber)",
        "ur": "آپ سے مل کر خوشی ہوئی {name} 🌟\nاپنا شعبہ منتخب کریں 👇 یا اپنے کام کا نام لکھیں (جیسے: پلمبر)",
    },
    "اختر مهنتك 👇": {"en": "Choose your trade 👇", "ur": "اپنا کام منتخب کریں 👇"},
    "اختر مهنتك من النتائج 👇": {"en": "Choose your trade from the results 👇", "ur": "نتائج میں سے اپنا کام منتخب کریں 👇"},
    "لم أجد مهنة باسم «{q}» 🤔\n\nاختر مهنتك من القائمة 👇 أو اكتب رقمها أو اسمها بصيغة أخرى": {
        "en": "I couldn't find a trade called «{q}» 🤔\n\nChoose your trade from the list 👇 or type its number or another name for it",
        "ur": "«{q}» نام کا کوئی کام نہیں ملا 🤔\n\nلسٹ سے اپنا کام منتخب کریں 👇 یا اس کا نمبر یا کوئی دوسرا نام لکھیں",
    },
    "ما الخدمات التي تقدمها في مهنة «{pname}»؟ 👇\nاضغط الزر، وحدّد كل خدماتك ☑️ ثم «تم التحديد».": {
        "en": "Which «{pname}» services do you offer? 👇\nTap the button, tick all your services ☑️ then «✅ تم التحديد» (Done).",
        "ur": "«{pname}» میں آپ کون سی سروسز دیتے ہیں؟ 👇\nبٹن دبائیں، اپنی تمام سروسز پر ☑️ لگائیں پھر «تم التحديد» دبائیں۔",
    },
    "اختر الخدمات": {"en": "Choose services", "ur": "سروسز چنیں"},
    "حدّد كل الخدمات التي تقدمها:": {"en": "Tick all the services you offer:", "ur": "اپنی تمام سروسز منتخب کریں:"},
    "📋 كل الخدمات": {"en": "📋 All services", "ur": "📋 تمام سروسز"},
    "✅ تم التحديد ({n})": {"en": "✅ Done ({n})", "ur": "✅ ہو گیا ({n})"},
    "الانتقال إلى الخطوة التالية": {"en": "Go to the next step", "ur": "اگلے مرحلے پر جائیں"},
    "أقدّم جميع خدمات المهنة": {"en": "I offer all services of this trade", "ur": "میں اس کام کی تمام سروسز دیتا ہوں"},
    "✅ اخترت: {items}\n\nاختر خدمة أخرى، أو اضغط «تم التحديد» 👇": {
        "en": "✅ Selected: {items}\n\nPick another service, or tap «Done» 👇",
        "ur": "✅ آپ نے چنا: {items}\n\nکوئی اور سروس چنیں، یا «ہو گیا» دبائیں 👇",
    },
    "ما الخدمات التي تقدمها في مهنة «{pname}»؟ 👇\nيمكنك اختيار أكثر من خدمة (واحدة بعد الأخرى)، أو «كل الخدمات».": {
        "en": "Which «{pname}» services do you offer? 👇\nYou can pick several (one after another), or «All services».",
        "ur": "«{pname}» میں آپ کون سی سروسز دیتے ہیں؟ 👇\nآپ ایک ایک کر کے کئی سروسز چن سکتے ہیں، یا «تمام سروسز»۔",
    },
    "الخدمات": {"en": "Services", "ur": "سروسز"},
    "👆 اضغط زر «اختر الخدمات» في الرسالة أعلاه.": {
        "en": "👆 Tap the «Choose services» button in the message above.",
        "ur": "👆 اوپر والے پیغام میں «سروسز چنیں» کا بٹن دبائیں۔",
    },
    "📍 شارك موقعك (مكان عملك أو منزلك) من الزر أدناه، لنحدد مدينتك وأقرب الأحياء إليك.": {
        "en": "📍 Share your location (work or home) using the button below, so we can find your city and nearest districts.",
        "ur": "📍 نیچے والے بٹن سے اپنی لوکیشن (کام یا گھر کی) بھیجیں، تاکہ ہم آپ کا شہر اور قریبی محلے معلوم کر سکیں۔",
    },
    "📍 شارك موقعك من الزر أدناه (أو 📎 ← الموقع) لنحدد مدينتك وأحياءك.": {
        "en": "📍 Share your location using the button below (or 📎 → Location) so we can find your city and districts.",
        "ur": "📍 نیچے والے بٹن سے اپنی لوکیشن بھیجیں (یا 📎 ← لوکیشن) تاکہ ہم آپ کا شہر اور محلے معلوم کر سکیں۔",
    },
    "لم نتمكن من تحديد مدينتك من هذا الموقع 😅 جرّب إرسال موقع آخر.": {
        "en": "We couldn't detect your city from this location 😅 Try sending another location.",
        "ur": "اس لوکیشن سے آپ کا شہر معلوم نہیں ہو سکا 😅 کوئی دوسری لوکیشن بھیج کر دیکھیں۔",
    },
    "🔎 أحيائي ليست هنا": {"en": "🔎 Not my districts", "ur": "🔎 میرے محلے یہاں نہیں"},
    "اعرض أحياء أخرى": {"en": "Show other districts", "ur": "دوسرے محلے دکھائیں"},
    "✔️ انتهيت ({n})": {"en": "✔️ Finished ({n})", "ur": "✔️ مکمل ({n})"},
    "أخدم المدينة كاملة": {"en": "I serve the whole city", "ur": "میں پورے شہر میں کام کرتا ہوں"},
    "✅ اخترت: {items}\nهل تريد إضافة حي آخر؟ 👇": {
        "en": "✅ Selected: {items}\nDo you want to add another district? 👇",
        "ur": "✅ آپ نے چنا: {items}\nکیا کوئی اور محلہ شامل کرنا ہے؟ 👇",
    },
    "ما الأحياء التي تخدمها في {city}؟ 👇 (يمكنك اختيار أكثر من حي)\nأو اكتب اسم الحي": {
        "en": "Which districts do you serve in {city}? 👇 (you can pick more than one)\nor type the district name",
        "ur": "{city} میں آپ کن محلوں میں کام کرتے ہیں؟ 👇 (ایک سے زیادہ چن سکتے ہیں)\nیا محلے کا نام لکھیں",
    },
    "أقرب الأحياء إليك": {"en": "Districts near you", "ur": "آپ کے قریبی محلے"},
    "ℹ️ وصلت إلى الحد الأقصى ({max} أحياء).\n": {
        "en": "ℹ️ You've reached the maximum ({max} districts).\n",
        "ur": "ℹ️ آپ زیادہ سے زیادہ حد ({max} محلے) تک پہنچ گئے۔\n",
    },
    "📋 حيّي ليس هنا": {"en": "📋 My district isn't here", "ur": "📋 میرا محلہ یہاں نہیں"},
    "كل أحياء {city} مرقّمة": {"en": "All {city} districts, numbered", "ur": "{city} کے تمام محلے، نمبر کے ساتھ"},
    "اعرض كل أحياء {city} مرقّمة": {"en": "Show all {city} districts, numbered", "ur": "{city} کے تمام محلے نمبر کے ساتھ دکھائیں"},
    "📍 {city} — ما الأحياء التي تعمل فيها؟ 👇\nاضغط الزر، وحدّد أحياءك ☑️ (حتى {max}) ثم «تم التحديد».": {
        "en": "📍 {city} — which districts do you work in? 👇\nTap the button, tick your districts ☑️ (up to {max}) then «✅ تم التحديد» (Done).",
        "ur": "📍 {city} — آپ کن محلوں میں کام کرتے ہیں؟ 👇\nبٹن دبائیں، اپنے محلوں پر ☑️ لگائیں ({max} تک) پھر «تم التحديد» دبائیں۔",
    },
    "اختر أحياءك": {"en": "Choose districts", "ur": "محلے چنیں"},
    "أقرب الأحياء إلى موقعك — حدّد حتى {max}:": {
        "en": "Districts nearest to your location — tick up to {max}:",
        "ur": "آپ کی لوکیشن کے قریبی محلے — {max} تک منتخب کریں:",
    },
    "الانتقال إلى المراجعة": {"en": "Go to review", "ur": "جائزے پر جائیں"},
    "📋 قائمة الأحياء كاملة": {"en": "📋 Full district list", "ur": "📋 محلوں کی پوری لسٹ"},
    "✅ اخترت: {items}\n\nاختر حيًّا آخر (حتى {max})، أو اضغط «تم التحديد» 👇": {
        "en": "✅ Selected: {items}\n\nPick another district (up to {max}), or tap «Done» 👇",
        "ur": "✅ آپ نے چنا: {items}\n\nکوئی اور محلہ چنیں ({max} تک)، یا «ہو گیا» دبائیں 👇",
    },
    "📍 {city} — ما الأحياء التي تعمل فيها؟ 👇\nهذه أقرب الأحياء إلى موقعك. يمكنك اختيار حتى {max} أحياء (واحدًا بعد الآخر).": {
        "en": "📍 {city} — which districts do you work in? 👇\nThese are the districts nearest to you. You can pick up to {max} (one after another).",
        "ur": "📍 {city} — آپ کن محلوں میں کام کرتے ہیں؟ 👇\nیہ آپ کی لوکیشن کے قریب ترین محلے ہیں۔ آپ ایک ایک کر کے {max} محلے تک چن سکتے ہیں۔",
    },
    "👆 اختر أحياءك من الرسالة أعلاه (زر «اختر الحي» أو «اختر أحياءك»).": {
        "en": "👆 Choose your districts from the message above («Choose district» or «Choose districts» button).",
        "ur": "👆 اوپر والے پیغام سے اپنے محلے چنیں («محلہ منتخب کریں» یا «محلے چنیں» کا بٹن)۔",
    },
    "🌍 خيار «المدينة كاملة» متاح للمهن النادرة فقط. اكتب أرقام أحيائك (حتى {max}) من القائمة 👆": {
        "en": "🌍 The «whole city» option is only for rare trades. Type your district numbers (up to {max}) from the list 👆",
        "ur": "🌍 «پورا شہر» کا آپشن صرف کم یاب کاموں کے لیے ہے۔ لسٹ سے اپنے محلوں کے نمبر لکھیں ({max} تک) 👆",
    },
    "🌍 كل {city} (المدينة كاملة)": {"en": "🌍 All of {city} (whole city)", "ur": "🌍 پورا {city} (پورا شہر)"},
    "📍 أحياء {city} (الأقرب إلى موقعك أولًا) 👇\nاكتب *أرقام* الأحياء التي تعمل فيها — حتى {max} أحياء، كل رقم في سطر، مثل:\n1\n4\n9": {
        "en": "📍 Districts of {city} (nearest to you first) 👇\nType the *numbers* of the districts you work in — up to {max}, one number per line, e.g.:\n1\n4\n9",
        "ur": "📍 {city} کے محلے (آپ کے قریب والے پہلے) 👇\nجن محلوں میں کام کرتے ہیں ان کے *نمبر* لکھیں — {max} تک، ہر نمبر الگ لائن میں، جیسے:\n1\n4\n9",
    },
    "✍️ اكتب أرقام أحيائك (حتى {max}).": {"en": "✍️ Type your district numbers (up to {max}).", "ur": "✍️ اپنے محلوں کے نمبر لکھیں ({max} تک)۔"},
    "هذه الأرقام غير موجودة في القائمة 🤔 اكتب أرقامًا من 1 إلى {n}.": {
        "en": "Those numbers aren't on the list 🤔 Type numbers from 1 to {n}.",
        "ur": "یہ نمبر لسٹ میں نہیں ہیں 🤔 1 سے {n} تک نمبر لکھیں۔",
    },
    "ℹ️ الحد الأقصى {max} أحياء — اعتمدنا أول {max}.\n": {
        "en": "ℹ️ The maximum is {max} districts — we kept the first {max}.\n",
        "ur": "ℹ️ زیادہ سے زیادہ {max} محلے — ہم نے پہلے {max} رکھ لیے۔\n",
    },
    "ℹ️ تجاهلنا أرقامًا غير موجودة: {nums}\n": {
        "en": "ℹ️ We ignored numbers that aren't on the list: {nums}\n",
        "ur": "ℹ️ لسٹ میں نہ ہونے والے نمبر چھوڑ دیے: {nums}\n",
    },
    "🔎 الأحياء التي تحتوي على «{q}»:\n{lines}\n\n✍️ اكتب *أرقام* أحيائك (حتى {max})، كل رقم في سطر.": {
        "en": "🔎 Districts containing «{q}»:\n{lines}\n\n✍️ Type your district *numbers* (up to {max}), one per line.",
        "ur": "🔎 وہ محلے جن میں «{q}» ہے:\n{lines}\n\n✍️ اپنے محلوں کے *نمبر* لکھیں ({max} تک)، ہر نمبر الگ لائن میں۔",
    },
    "✍️ اكتب *أرقام* الأحياء من القائمة أعلاه 👆 (حتى {max})، كل رقم في سطر، مثل:\n12\n40\n7": {
        "en": "✍️ Type the district *numbers* from the list above 👆 (up to {max}), one per line, e.g.:\n12\n40\n7",
        "ur": "✍️ اوپر والی لسٹ سے محلوں کے *نمبر* لکھیں 👆 ({max} تک)، ہر نمبر الگ لائن میں، جیسے:\n12\n40\n7",
    },
    "أو اكتب اسم الحي لأعرض لك رقمه.": {
        "en": "Or type the district name and I'll show you its number.",
        "ur": "یا محلے کا نام لکھیں، میں آپ کو اس کا نمبر بتا دوں گا۔",
    },
    "🌍 أو # لكل المدينة.": {"en": "🌍 Or # for the whole city.", "ur": "🌍 یا پورے شہر کے لیے #۔"},
    "لم أجد حيًّا بهذا الاسم في {city} 🤔": {
        "en": "I couldn't find a district with that name in {city} 🤔",
        "ur": "{city} میں اس نام کا کوئی محلہ نہیں ملا 🤔",
    },
    "{note}راجع بياناتك قبل التسجيل 👇\n\n👷 {name}\n🛠️ {pname}\n📋 {services}\n📍 {country} / {where}\n📱 رقم التواصل للعملاء: +{phone}": {
        "en": "{note}Review your details before registering 👇\n\n👷 {name}\n🛠️ {pname}\n📋 {services}\n📍 {country} / {where}\n📱 Contact number for customers: +{phone}",
        "ur": "{note}رجسٹریشن سے پہلے اپنی معلومات چیک کریں 👇\n\n👷 {name}\n🛠️ {pname}\n📋 {services}\n📍 {country} / {where}\n📱 گاہکوں کے لیے رابطہ نمبر: +{phone}",
    },
    "✅ تأكيد التسجيل": {"en": "✅ Confirm", "ur": "✅ تصدیق کریں"},
    "📍 تعديل الأحياء": {"en": "📍 Edit districts", "ur": "📍 محلے تبدیل کریں"},
    "✏️ البدء من جديد": {"en": "✏️ Start over", "ur": "✏️ دوبارہ شروع"},
    "👆 اضغط «✅ تأكيد التسجيل» في الرسالة أعلاه، أو «✏️ البدء من جديد».": {
        "en": "👆 Tap «✅ Confirm» in the message above, or «✏️ Start over».",
        "ur": "👆 اوپر والے پیغام میں «✅ تصدیق کریں» دبائیں، یا «✏️ دوبارہ شروع»۔",
    },
    "الرقم +{phone} مسجّل مسبقًا في «فنّي».": {
        "en": "The number +{phone} is already registered on «Fanni».",
        "ur": "نمبر +{phone} پہلے سے «فنی» پر رجسٹرڈ ہے۔",
    },
    "🎉 تم تسجيل الفني «{name}» على الرقم +{phone}، وأصبح يظهر للعملاء.\n\n": {
        "en": "🎉 Technician «{name}» is registered on +{phone} and now appears to customers.\n\n",
        "ur": "🎉 ٹیکنیشن «{name}» نمبر +{phone} پر رجسٹر ہو گیا، اب گاہکوں کو نظر آئے گا۔\n\n",
    },
    "➕ تسجيل فني آخر": {"en": "➕ Register another", "ur": "➕ دوسرا رجسٹر کریں"},
    "🎉 تم تسجيلك! وأصبحت تظهر للعملاء الذين يبحثون في واتساب وتلغرام.\n\nهذه بطاقتك كما يراها العميل:\n\n": {
        "en": "🎉 You're registered! Customers searching on WhatsApp and Telegram can now find you.\n\nHere's your card as customers see it:\n\n",
        "ur": "🎉 آپ رجسٹر ہو گئے! اب واٹس ایپ اور ٹیلیگرام پر تلاش کرنے والے گاہک آپ کو دیکھ سکتے ہیں۔\n\nگاہک کو آپ کا کارڈ ایسا نظر آئے گا:\n\n",
    },
    "هل تريد إضافة بياناتك في تطبيق تلغرام أيضًا؟ 🔗\nستصلك هناك تنبيهات العملاء مجانًا، ويمكنك إدارة حسابك واشتراكك.": {
        "en": "Do you want to add your details on Telegram too? 🔗\nYou'll get customer alerts there for free and can manage your account and subscription.",
        "ur": "کیا آپ اپنی معلومات ٹیلیگرام پر بھی شامل کرنا چاہتے ہیں؟ 🔗\nوہاں گاہکوں کے نوٹیفکیشن مفت ملیں گے، اور آپ اپنا اکاؤنٹ اور سبسکرپشن سنبھال سکیں گے۔",
    },
    "✅ نعم، أضفها": {"en": "✅ Yes, add it", "ur": "✅ ہاں، شامل کریں"},
    "لا، شكرًا": {"en": "No, thanks", "ur": "نہیں، شکریہ"},
    "حسابك مربوط بتلغرام بالفعل ✅": {"en": "Your account is already linked to Telegram ✅", "ur": "آپ کا اکاؤنٹ پہلے سے ٹیلیگرام سے جڑا ہوا ہے ✅"},
    "اضغط الزر، ثم اضغط «ابدأ» (Start) في تلغرام — وسيُربط حسابك تلقائيًا ✅": {
        "en": "Tap the button, then tap «Start» in Telegram — your account will be linked automatically ✅",
        "ur": "بٹن دبائیں، پھر ٹیلیگرام میں «Start» دبائیں — آپ کا اکاؤنٹ خود بخود جڑ جائے گا ✅",
    },
    "فتح تلغرام": {"en": "Open Telegram", "ur": "ٹیلیگرام کھولیں"},
    "🔕 تم إيقاف الإشعارات. إذا أردت إعادة تفعيلها فتواصل مع إدارة «فنّي».": {
        "en": "🔕 Notifications turned off. To turn them back on, contact the «Fanni» team.",
        "ur": "🔕 نوٹیفکیشن بند کر دیے گئے۔ دوبارہ چالو کرنے کے لیے «فنی» انتظامیہ سے رابطہ کریں۔",
    },
    "حسنًا 👍 يمكنك ربطه في أي وقت من «🛠️ أنا فني». اكتب s للعودة إلى القائمة.": {
        "en": "OK 👍 You can link it anytime from «🛠️ I'm a technician». Type s to go back to the menu.",
        "ur": "ٹھیک ہے 👍 آپ کسی بھی وقت «🛠️ میں ٹیکنیشن ہوں» سے جوڑ سکتے ہیں۔ مینو پر واپس جانے کے لیے s لکھیں۔",
    },

    # ─────────── الاشتراك والدفع ───────────
    "✅ اشتراكك فعّال حتى {date} — تظهر لجميع العملاء دون حد.": {
        "en": "✅ Your subscription is active until {date} — you're shown to all customers without limits.",
        "ur": "✅ آپ کی سبسکرپشن {date} تک فعال ہے — آپ بغیر حد کے تمام گاہکوں کو نظر آتے ہیں۔",
    },
    "الاشتراك عبر واتساب غير متاح في دولتك حاليًا 🙏 يمكنك الاشتراك بنجوم تلغرام عن طريق بوت «فنّي»: {url}": {
        "en": "Subscribing via WhatsApp isn't available in your country yet 🙏 You can subscribe with Telegram Stars through the «Fanni» bot: {url}",
        "ur": "آپ کے ملک میں ابھی واٹس ایپ سے سبسکرپشن دستیاب نہیں 🙏 آپ «فنی» بوٹ کے ذریعے ٹیلیگرام اسٹارز سے سبسکرائب کر سکتے ہیں: {url}",
    },
    "⚠️ الدفع غير متاح حاليًا — حاول بعد قليل أو تواصل مع الإدارة.": {
        "en": "⚠️ Payment isn't available right now — try again shortly or contact the team.",
        "ur": "⚠️ ابھی ادائیگی دستیاب نہیں — تھوڑی دیر بعد کوشش کریں یا انتظامیہ سے رابطہ کریں۔",
    },
    "⚠️ حدث خطأ في بوابة الدفع. حاول مرة أخرى بعد قليل.": {
        "en": "⚠️ Something went wrong with the payment gateway. Please try again shortly.",
        "ur": "⚠️ پیمنٹ گیٹ وے میں خرابی ہوئی۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
    },
    "💳 اشتراك شهري ({days} يومًا) — {price} ريال\nتظهر لجميع العملاء دون حدود.\n\nادفع بمدى أو فيزا أو آبل باي من الزر أدناه، وبعد إتمام الدفع عُد إلى هنا واكتب «دفعت» ✅": {
        "en": "💳 Monthly subscription ({days} days) — {price} SAR\nYou'll be shown to all customers without limits.\n\nPay with mada, Visa or Apple Pay using the button below, then come back here and type «paid» ✅",
        "ur": "💳 ماہانہ سبسکرپشن ({days} دن) — {price} ریال\nآپ بغیر حد کے تمام گاہکوں کو نظر آئیں گے۔\n\nنیچے والے بٹن سے مدیٰ، ویزا یا ایپل پے کے ذریعے ادائیگی کریں، پھر یہاں واپس آ کر «paid» لکھیں ✅",
    },
    "ادفع الآن": {"en": "Pay now", "ur": "ابھی ادائیگی کریں"},
    "✅ تم تفعيل اشتراكك في «فنّي» — {days} يومًا (حتى {date}).\nمن الآن ستظهر لجميع العملاء الذين يبحثون عن خدمتك دون حد 👌": {
        "en": "✅ Your «Fanni» subscription is active — {days} days (until {date}).\nFrom now on you'll be shown to every customer searching for your service, without limits 👌",
        "ur": "✅ «فنی» میں آپ کی سبسکرپشن فعال ہو گئی — {days} دن ({date} تک)۔\nاب سے آپ اپنی سروس تلاش کرنے والے تمام گاہکوں کو بغیر حد کے نظر آئیں گے 👌",
    },
    "لم يصلنا تأكيد الدفع بعد ⏳ إذا كنت قد دفعت فعلًا، فانتظر دقيقة ثم اكتب «دفعت» مرة أخرى.": {
        "en": "We haven't received payment confirmation yet ⏳ If you've already paid, wait a minute and type «paid» again.",
        "ur": "ابھی ادائیگی کی تصدیق نہیں ملی ⏳ اگر آپ ادائیگی کر چکے ہیں تو ایک منٹ انتظار کریں پھر دوبارہ «paid» لکھیں۔",
    },
    "✅ اشتراكك فعّال حتى {date}، ورقمك يظهر لجميع العملاء.": {
        "en": "✅ Your subscription is active until {date}, and your number is shown to all customers.",
        "ur": "✅ آپ کی سبسکرپشن {date} تک فعال ہے، اور آپ کا نمبر تمام گاہکوں کو نظر آتا ہے۔",
    },
    "📊 فرص التواصل المجانية: استُخدمت {used} من {limit}.": {
        "en": "📊 Free contacts: {used} of {limit} used.",
        "ur": "📊 مفت رابطے: {limit} میں سے {used} استعمال ہو چکے۔",
    },
    "⚠️ رقمك لا يظهر حاليًا في نتائج البحث.": {
        "en": "⚠️ Your number isn't currently shown in search results.",
        "ur": "⚠️ ابھی آپ کا نمبر تلاش کے نتائج میں نظر نہیں آ رہا۔",
    },
    "💳 الاشتراك الشهري ({days} يومًا) بـ {price} ريال يُظهر رقمك لجميع العملاء دون حد.": {
        "en": "💳 The monthly subscription ({days} days) for {price} SAR shows your number to all customers without limits.",
        "ur": "💳 ماہانہ سبسکرپشن ({days} دن) صرف {price} ریال میں آپ کا نمبر تمام گاہکوں کو بغیر حد کے دکھاتی ہے۔",
    },
    "💳 اشترك الآن": {"en": "💳 Subscribe now", "ur": "💳 ابھی سبسکرائب"},
    "🔕 إيقاف الإشعارات": {"en": "🔕 Mute alerts", "ur": "🔕 نوٹیفکیشن بند"},
    "حسابك في «فنّي» 👷 {name}\n🛠️ {pname}\n\n{line}": {
        "en": "Your «Fanni» account 👷 {name}\n🛠️ {pname}\n\n{line}",
        "ur": "«فنی» میں آپ کا اکاؤنٹ 👷 {name}\n🛠️ {pname}\n\n{line}",
    },

    # ─────────── أوصاف المهن الأكثر طلبًا (top.DESCS) ───────────
    "مكيفات، ثلاجات، غسالات ملابس": {"en": "ACs, fridges, washing machines", "ur": "اے سی، فریج، واشنگ مشین"},
    "تسريب، انسداد، خلاطات، سخانات": {"en": "Leaks, blockages, mixers, water heaters", "ur": "لیکیج، بند نالیاں، مکسر، گیزر"},
    "التماس، تركيب إنارة، لوحات كهرباء": {"en": "Short circuits, lighting, electrical panels", "ur": "شارٹ سرکٹ، لائٹیں لگانا، بجلی کے بورڈ"},
    "صراصير، نمل أبيض، بق الفراش": {"en": "Cockroaches, termites, bed bugs", "ur": "لال بیگ، دیمک، کھٹمل"},
    "فك وتركيب ونقل أثاث، دينا": {"en": "Furniture moving & assembly, truck", "ur": "فرنیچر کھولنا، لگانا اور شفٹنگ، ڈائنا"},
    "فك وتركيب غرف نوم، خزائن، أثاث": {"en": "Bedroom sets, wardrobes, furniture assembly", "ur": "بیڈروم سیٹ، الماریاں، فرنیچر کھولنا اور لگانا"},
    "ترميم، دهان الشقق، طلاء الجدران": {"en": "Renovation, apartment & wall painting", "ur": "مرمت، فلیٹ کا رنگ، دیواروں کا پینٹ"},
    "تركيب دش، برمجة، كاميرات مراقبة": {"en": "Dish install, receiver setup, CCTV", "ur": "ڈش لگانا، رسیور سیٹنگ، سی سی ٹی وی کیمرے"},
    "شبابيك، أبواب، مطابخ ألمنيوم": {"en": "Aluminium windows, doors, kitchens", "ur": "المونیم کی کھڑکیاں، دروازے، کچن"},
    "أبواب خشب، خزائن، ديكور": {"en": "Wooden doors, cabinets, decor", "ur": "لکڑی کے دروازے، الماریاں، ڈیکور"},
    "عدم تصريف، تسريب، لا تسخّن": {"en": "Not draining, leaking, not heating", "ur": "پانی نہیں نکلتا، لیکیج، گرم نہیں کرتا"},
    "أفران غاز وكهرباء وبلت إن": {"en": "Gas, electric & built-in ovens", "ur": "گیس، بجلی اور بلٹ اِن اوون"},
}


SERVICES: dict[str, dict[str, str]] = {
    "تفصيل وتركيب الأبواب": {"en": "Doors: make & install", "ur": "دروازے بنانا اور لگانا"},
    "إصلاح الأبواب": {"en": "Door repair", "ur": "دروازوں کی مرمت"},
    "أعمال الديكور الخشبي": {"en": "Wood decor work", "ur": "لکڑی کا ڈیکور"},
    "تفصيل وتركيب الخزائن": {"en": "Cabinets: make & install", "ur": "الماریاں بنانا اور لگانا"},
    "تفصيل الأثاث الخشبي": {"en": "Custom wooden furniture", "ur": "لکڑی کا فرنیچر بنانا"},
    "تركيب البلاط": {"en": "Tile installation", "ur": "ٹائل لگانا"},
    "تركيب السيراميك": {"en": "Ceramic installation", "ur": "سیرامک لگانا"},
    "تركيب البورسلان": {"en": "Porcelain installation", "ur": "پورسلین لگانا"},
    "إصلاح واستبدال البلاط": {"en": "Tile repair & replace", "ur": "ٹائل کی مرمت اور تبدیلی"},
    "تركيب بلاط الأرضيات والجدران": {"en": "Floor & wall tiling", "ur": "فرش اور دیوار کی ٹائلیں"},
    "تركيب الزجاج": {"en": "Glass installation", "ur": "شیشہ لگانا"},
    "استبدال الزجاج": {"en": "Glass replacement", "ur": "شیشہ تبدیل کرنا"},
    "تفصيل الزجاج": {"en": "Custom glass cutting", "ur": "شیشہ کاٹنا اور بنانا"},
    "تركيب واجهات زجاجية": {"en": "Glass facades", "ur": "شیشے کے فرنٹ لگانا"},
    "تركيب المرايا": {"en": "Mirror installation", "ur": "آئینہ لگانا"},
    "إصلاح تسربات المياه": {"en": "Water leak repair", "ur": "پانی کی لیکیج کی مرمت"},
    "تمديد وإصلاح المواسير": {"en": "Pipe fitting & repair", "ur": "پائپ لگانا اور مرمت"},
    "تركيب الأدوات الصحية": {"en": "Sanitary fixtures", "ur": "سینیٹری کا سامان لگانا"},
    "تركيب الخلاطات": {"en": "Mixer tap installation", "ur": "مکسر لگانا"},
    "تركيب وصيانة مضخات المياه": {"en": "Water pump service", "ur": "واٹر پمپ لگانا/مرمت"},
    "تسليك المجاري": {"en": "Drain unblocking", "ur": "گٹر/نالی کھولنا"},
    "صيانة مكيفات": {"en": "AC maintenance", "ur": "اے سی کی سروس"},
    "إصلاح أعطال المكيفات": {"en": "AC fault repair", "ur": "اے سی کی خرابی ٹھیک کرنا"},
    "تركيب مكيفات": {"en": "AC installation", "ur": "اے سی لگانا"},
    "فك وتركيب المكيفات": {"en": "AC removal & reinstall", "ur": "اے سی کھولنا اور لگانا"},
    "شحن فريون": {"en": "Freon refill", "ur": "فریون گیس بھرنا"},
    "تمديد مواسير التكييف": {"en": "AC pipe installation", "ur": "اے سی کے پائپ لگانا"},
    "صيانة ثلاجات وفريزرات": {"en": "Fridge & freezer repair", "ur": "فریج اور فریزر کی مرمت"},
    "صيانة غسالات ملابس": {"en": "Washing machine repair", "ur": "واشنگ مشین کی مرمت"},
    "صيانة مكانس كهربائية": {"en": "Vacuum cleaner repair", "ur": "ویکیوم کلینر کی مرمت"},
    "برادات مياه": {"en": "Water coolers", "ur": "واٹر کولر"},
    "دهان داخلي": {"en": "Interior painting", "ur": "اندرونی رنگ"},
    "دهان خارجي": {"en": "Exterior painting", "ur": "بیرونی رنگ"},
    "دهانات الديكور": {"en": "Decorative paints", "ur": "ڈیکوریشن پینٹ"},
    "معالجة وتجهيز الجدران": {"en": "Wall prep & treatment", "ur": "دیواروں کی تیاری"},
    "إعادة دهان الأسطح": {"en": "Surface repainting", "ur": "دوبارہ رنگ کرنا"},
    "تركيب الرخام": {"en": "Marble installation", "ur": "ماربل لگانا"},
    "قص وتفصيل الرخام": {"en": "Marble cutting", "ur": "ماربل کاٹنا"},
    "جلي وتلميع الرخام": {"en": "Marble polishing", "ur": "ماربل پالش"},
    "إصلاح الرخام": {"en": "Marble repair", "ur": "ماربل کی مرمت"},
    "تركيب أسطح المطابخ": {"en": "Kitchen countertops", "ur": "کچن کاؤنٹر ٹاپ لگانا"},
    "تركيب الدرج الرخامي": {"en": "Marble stairs", "ur": "ماربل کی سیڑھیاں"},
    "تركيب أسقف مستعارة (أرمسترونق وغيرها)": {"en": "False ceilings", "ur": "فالس سیلنگ"},
    "تركيب فواصل جبسية": {"en": "Gypsum partitions", "ur": "جپسم پارٹیشن"},
    "ديكورات جبسية": {"en": "Gypsum decor", "ur": "جپسم ڈیکور"},
    "تركيب إضاءة مخفية بالجبس": {"en": "Hidden gypsum lighting", "ur": "جپسم میں چھپی لائٹیں"},
    "تأسيس وتمديد الكهرباء": {"en": "Electrical wiring", "ur": "بجلی کی وائرنگ"},
    "إصلاح الأعطال الكهربائية": {"en": "Electrical fault repair", "ur": "بجلی کی خرابی ٹھیک کرنا"},
    "تركيب الأفياش والمفاتيح": {"en": "Sockets & switches", "ur": "ساکٹ اور سوئچ لگانا"},
    "تركيب الإنارة": {"en": "Lighting installation", "ur": "لائٹیں لگانا"},
    "تركيب اللوحات والقواطع": {"en": "Panels & breakers", "ur": "بورڈ اور بریکر لگانا"},
    "تركيب وإصلاح أجهزة المنزل الكهربائية": {"en": "Home appliances", "ur": "گھریلو برقی آلات"},
    "تركيب فلاتر المياه": {"en": "Water filter install", "ur": "پانی کا فلٹر لگانا"},
    "صيانة فلاتر المياه": {"en": "Water filter service", "ur": "پانی کے فلٹر کی سروس"},
    "تغيير الفلاتر": {"en": "Filter replacement", "ur": "فلٹر تبدیل کرنا"},
    "إصلاح أجهزة تنقية المياه": {"en": "Water purifier repair", "ur": "واٹر پیوریفائر کی مرمت"},
    "تركيب أنظمة تنقية المياه": {"en": "Water purifier systems", "ur": "واٹر پیوریفائر سسٹم"},
    "غسالات أوتوماتيك": {"en": "Automatic washers", "ur": "آٹومیٹک واشنگ مشین"},
    "غسالات عادية": {"en": "Twin-tub washers", "ur": "عام واشنگ مشین"},
    "ثلاجات": {"en": "Fridges", "ur": "فریج"},
    "نشافات": {"en": "Dryers", "ur": "ڈرائر"},
    "مكانس كهربائية": {"en": "Vacuum cleaners", "ur": "ویکیوم کلینر"},
    "مكيفات متنقلة": {"en": "Portable ACs", "ur": "پورٹیبل اے سی"},
    "أجهزة منزلية أخرى": {"en": "Other appliances", "ur": "دیگر گھریلو آلات"},
    "الأبواب الحديدية": {"en": "Iron doors", "ur": "لوہے کے دروازے"},
    "النوافذ والحواجز": {"en": "Windows & railings", "ur": "کھڑکیاں اور ریلنگ"},
    "المظلات": {"en": "Shades & canopies", "ur": "شیڈ اور سائبان"},
    "السلالم الحديدية": {"en": "Iron stairs", "ur": "لوہے کی سیڑھیاں"},
    "أعمال الحديد المختلفة": {"en": "General ironwork", "ur": "لوہے کے مختلف کام"},
    "تشخيص الأعطال الكهربائية": {"en": "Electrical diagnostics", "ur": "بجلی کی خرابی کی جانچ"},
    "إصلاح كهرباء السيارة": {"en": "Car electrical repair", "ur": "گاڑی کی بجلی کی مرمت"},
    "البطاريات": {"en": "Batteries", "ur": "بیٹریاں"},
    "الدينمو": {"en": "Alternator", "ur": "ڈائنمو"},
    "السلف": {"en": "Starter motor", "ur": "سیلف"},
    "الإضاءة": {"en": "Lighting", "ur": "لائٹیں"},
    "أنظمة التشغيل (كهرباء سيارات)": {"en": "Car electrical systems", "ur": "گاڑی کے برقی نظام"},
    "تفصيل وتركيب النوافذ": {"en": "Custom windows & install", "ur": "کھڑکیاں بنانا اور لگانا"},
    "إصلاح الألمنيوم": {"en": "Aluminium repair", "ur": "المونیم کی مرمت"},
    "تركيب المطابخ": {"en": "Kitchen installation", "ur": "کچن لگانا"},
    "أعمال الألمنيوم المختلفة": {"en": "General aluminium work", "ur": "المونیم کے مختلف کام"},
    "فك وتركيب غرف نوم": {"en": "Bedroom set assembly", "ur": "بیڈروم سیٹ فٹنگ"},
    "فك وتركيب دواليب": {"en": "Wardrobe assembly", "ur": "الماری کھولنا اور لگانا"},
    "تفصيل أثاث خشبي": {"en": "Custom wooden furniture", "ur": "لکڑی کا فرنیچر بنانا"},
    "إصلاح الأثاث": {"en": "Furniture repair", "ur": "فرنیچر کی مرمت"},
    "تركيب مطابخ خشب": {"en": "Wooden kitchens", "ur": "لکڑی کے کچن لگانا"},
    "فتح الأقفال": {"en": "Lock opening", "ur": "تالا کھولنا"},
    "إصلاح الأقفال": {"en": "Lock repair", "ur": "تالے کی مرمت"},
    "تركيب الأقفال": {"en": "Lock installation", "ur": "تالا لگانا"},
    "تغيير الأقفال": {"en": "Lock replacement", "ur": "تالا تبدیل کرنا"},
    "نسخ وبرمجة المفاتيح": {"en": "Key copying & coding", "ur": "چابی بنانا اور پروگرامنگ"},
    "تصفيف شعر": {"en": "Hair styling", "ur": "ہیئر اسٹائلنگ"},
    "تسريحات مناسبات وعرايس": {"en": "Event & bridal hair", "ur": "دلہن/تقریب ہیئر اسٹائل"},
    "صبغة وعناية بالشعر (خدمة منزلية أو صالون)": {"en": "Hair colour & care", "ur": "بالوں کا رنگ اور کیئر"},
    "مكياج مناسبات وأعراس": {"en": "Event & wedding makeup", "ur": "تقریب اور شادی کا میک اپ"},
    "مكياج خفيف يومي": {"en": "Light everyday makeup", "ur": "روزانہ کا ہلکا میک اپ"},
    "خدمة منزلية أو بالصالون": {"en": "At home or in salon", "ur": "گھر پر یا سیلون میں"},
    "نقل الأثاث": {"en": "Furniture moving", "ur": "فرنیچر شفٹنگ"},
    "فك وتركيب الأثاث": {"en": "Furniture assembly", "ur": "فرنیچر کھولنا اور لگانا"},
    "نقل الأجهزة المنزلية": {"en": "Appliance moving", "ur": "گھریلو آلات کی شفٹنگ"},
    "تغليف الأثاث": {"en": "Furniture packing", "ur": "فرنیچر کی پیکنگ"},
    "رفع الأثاث": {"en": "Furniture lifting", "ur": "فرنیچر اوپر چڑھانا"},
    "سحب سيارة معطلة": {"en": "Broken-down car towing", "ur": "خراب گاڑی کھینچنا"},
    "نقل سيارة بعد حادث": {"en": "Accident car transport", "ur": "حادثے والی گاڑی لے جانا"},
    "سحب داخل المدينة": {"en": "Towing within city", "ur": "شہر کے اندر ٹوئنگ"},
    "سحب بين المدن": {"en": "Intercity towing", "ur": "شہروں کے درمیان ٹوئنگ"},
    "تحميل وتفريغ البضائع": {"en": "Loading & unloading", "ur": "سامان لوڈ/ان لوڈ"},
    "نقل البضائع داخل المستودع/المحل": {"en": "In-store goods moving", "ur": "گودام میں سامان منتقلی"},
    "ترتيب وتنظيم البضائع": {"en": "Arranging goods", "ur": "سامان کی ترتیب"},
    "مناولة بضائع بمعدات يدوية": {"en": "Manual goods handling", "ur": "سامان کی دستی ہینڈلنگ"},
    "صيانة المسابح": {"en": "Pool maintenance", "ur": "سوئمنگ پول کی دیکھ بھال"},
    "تنظيف وصيانة أنظمة المسابح": {"en": "Pool system cleaning", "ur": "پول سسٹم کی صفائی"},
    "صيانة المضخات": {"en": "Pump maintenance", "ur": "پمپ کی سروس"},
    "صيانة الفلاتر": {"en": "Filter maintenance", "ur": "فلٹر کی سروس"},
    "إصلاح تسربات المسابح": {"en": "Pool leak repair", "ur": "پول کی لیکیج کی مرمت"},
    "مكافحة الحشرات": {"en": "Pest control", "ur": "کیڑے مار اسپرے"},
    "مكافحة القوارض": {"en": "Rodent control", "ur": "چوہوں کا خاتمہ"},
    "مكافحة النمل": {"en": "Ant control", "ur": "چیونٹیوں کا خاتمہ"},
    "مكافحة الصراصير": {"en": "Cockroach control", "ur": "لال بیگ کا خاتمہ"},
    "مكافحة البق": {"en": "Bed bug control", "ur": "کھٹمل کا خاتمہ"},
    "مكافحة الحشرات الطائرة": {"en": "Flying insect control", "ur": "اڑنے والے کیڑوں کا خاتمہ"},
    "تركيب دش": {"en": "Dish installation", "ur": "ڈش لگانا"},
    "برمجة رسيفر": {"en": "Receiver setup", "ur": "رسیور سیٹنگ"},
    "كاميرات مراقبة": {"en": "CCTV cameras", "ur": "سی سی ٹی وی کیمرے"},
    "انتركم وجرس": {"en": "Intercom & doorbell", "ur": "انٹرکام اور گھنٹی"},
    "شبكات واي فاي": {"en": "Wi-Fi networks", "ur": "وائی فائی نیٹ ورک"},
    "عدم التصريف": {"en": "Not draining", "ur": "پانی نہیں نکلتا"},
    "تسريب ماء": {"en": "Water leak", "ur": "پانی لیک ہونا"},
    "ما تسخّن": {"en": "Not heating", "ur": "گرم نہیں کرتا"},
    "تركيب غسالة صحون": {"en": "Dishwasher installation", "ur": "ڈش واشر لگانا"},
    "تغيير قطع": {"en": "Parts replacement", "ur": "پرزے تبدیل کرنا"},
    "أفران غاز": {"en": "Gas ovens", "ur": "گیس اوون"},
    "أفران كهرباء": {"en": "Electric ovens", "ur": "بجلی کے اوون"},
    "أفران مدمجة (بلت إن)": {"en": "Built-in ovens", "ur": "بلٹ اِن اوون"},
    "تركيب فرن": {"en": "Oven installation", "ur": "اوون لگانا"},
    "تغيير قطع وحساسات": {"en": "Parts & sensors change", "ur": "پرزے/سینسر تبدیل کرنا"},
    "نجارة القواعد والأعمدة": {"en": "Footing/column formwork", "ur": "بنیاد اور ستون کی شٹرنگ"},
    "نجارة الأسقف والصبّات": {"en": "Slab & roof formwork", "ur": "چھت اور سلیب کی شٹرنگ"},
    "تركيب الشدات الخشبية": {"en": "Wooden formwork setup", "ur": "لکڑی کی شٹرنگ لگانا"},
    "فك الشدات": {"en": "Formwork removal", "ur": "شٹرنگ کھولنا"},
}
